version: '2'
services: 
    angular-service: 
      container_name: angularcontainer  
      build: ./
      volumes: 
        - './:/usr/src/app' 
      ports: 
        - '4200:4200' # Port mapping
      command: > 
        bash -c "ng serve"